#! /usr/bin/env python
# plotting options
#---------------------

sam_opt = {
    ########## Data ##########
   'SingleMuonRun2016B-v1' : {
        'sam_name'  : 'SingleMuonRun2016B-PromptReco-v1',
        'order'     : 0,
        'fillcolor' : 1, #kBlack
        'fillstyle' : 1,
        'linecolor' : 1,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'Data',
    },
   'SingleMuonRun2016B-v2' : {
        'sam_name'  : 'SingleMuonRun2016B-PromptReco-v2',
        'order'     : 0,
        'fillcolor' : 1,
        'fillstyle' : 1,
        'linecolor' : 1,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'Data',
    },
   'SingleMuonRun2016C-v2' : {
        'sam_name'  : 'SingleMuonRun2016C-PromptReco-v2',
        'order'     : 0,
        'fillcolor' : 1,
        'fillstyle' : 1,
        'linecolor' : 1,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'Data',
    },
   'SingleMuonRun2016D-v2' : {
        'sam_name'  : 'SingleMuonRun2016D-PromptReco-v2',
        'order'     : 0,
        'fillcolor' : 1,
        'fillstyle' : 1,
        'linecolor' : 1,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'Data',
    },
   'SingleMuonRun2016H-PromptReco-v1' : {
        'sam_name': 'SingleMuonRun2016H-PromptReco-v1',
        'order'     : 0,
        'fillcolor' : 1,
        'fillstyle' : 1,
        'linecolor' : 1,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'Data',
    },
   'SingleMuonRun2016H-PromptReco-v2' : {
        'sam_name': 'SingleMuonRun2016H-PromptReco-v2',
        'order'     : 0,
        'fillcolor' : 1,
        'fillstyle' : 1,
        'linecolor' : 1,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'Data',
    },
    'SingleMuonRun2016H-PromptReco-v3' : {
        'sam_name': 'SingleMuonRun2016H-PromptReco-v3',
        'order'     : 0,
        'fillcolor' : 1,
        'fillstyle' : 1,
        'linecolor' : 1,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'Data',
    },
    #re-reco 
    'SingleMuonRun2016B-23Sep2016-v1' : {
        'sam_name': 'SingleMuonRun2016B-23Sep2016-v1',
        'order'     : 0,
        'fillcolor' : 1,
        'fillstyle' : 1,
        'linecolor' : 1,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'Data',
    },
    'SingleMuonRun2016B-23Sep2016-v3' : {
        'sam_name': 'SingleMuonRun2016B-23Sep2016-v3',
        'order'     : 0,
        'fillcolor' : 1,
        'fillstyle' : 1,
        'linecolor' : 1,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'Data',
    },
    'SingleMuonRun2016C-23Sep2016-v1' : {
        'sam_name': 'SingleMuonRun2016C-23Sep2016-v1',
        'order'     : 0,
        'fillcolor' : 1,
        'fillstyle' : 1,
        'linecolor' : 1,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'Data',
    },
    'SingleMuonRun2016D-23Sep2016-v1' : {
        'sam_name': 'SingleMuonRun2016D-23Sep2016-v1',
        'order'     : 0,
        'fillcolor' : 1,
        'fillstyle' : 1,
        'linecolor' : 1,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'Data',
    },
    'SingleMuonRun2016E-23Sep2016-v1' : {
        'sam_name': 'SingleMuonRun2016E-23Sep2016-v1',
        'order'     : 0,
        'fillcolor' : 1,
        'fillstyle' : 1,
        'linecolor' : 1,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'Data',
    },
    'SingleMuonRun2016F-23Sep2016-v1' : {
        'sam_name': 'SingleMuonRun2016F-23Sep2016-v1',
        'order'     : 0,
        'fillcolor' : 1,
        'fillstyle' : 1,
        'linecolor' : 1,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'Data',
    },
    'SingleMuonRun2016G-23Sep2016-v1' : {
        'sam_name': 'SingleMuonRun2016G-23Sep2016-v1',
        'order'     : 0,
        'fillcolor' : 1,
        'fillstyle' : 1,
        'linecolor' : 1,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'Data',
    },

   'BTagCSVRun2016B-v1' : {
        'sam_name'  : 'BTagCSVRun2016B-PromptReco-v1',
        'order'     : 0,
        'fillcolor' : 1,
        'fillstyle' : 1,
        'linecolor' : 1,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'Data',
    },
   'BTagCSVRun2016B-v2' : {
        'sam_name'  : 'BTagCSVRun2016B-PromptReco-v2',
        'order'     : 0,
        'fillcolor' : 1,
        'fillstyle' : 1,
        'linecolor' : 1,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'Data',
    },
   'BTagCSVRun2016C-v2' : {
        'sam_name'  : 'BTagCSVRun2016C-PromptReco-v2',
        'order'     : 0,
        'fillcolor' : 1,
        'fillstyle' : 1,
        'linecolor' : 1,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'Data',
    },
   'BTagCSVRun2016D-v2' : {
        'sam_name'  : 'BTagCSVRun2016D-PromptReco-v2',
        'order'     : 0,
        'fillcolor' : 1,
        'fillstyle' : 1,
        'linecolor' : 1,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'Data',
    },
   
   'BTagCSVRun2016H-PromptReco-v2' : {
        'sam_name'  : 'BTagCSVRun2016H-PromptReco-v2',
        'order'     : 0,
        'fillcolor' : 1,
        'fillstyle' : 1,
        'linecolor' : 1,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'Data',
    },
    'BTagCSVRun2016H-PromptReco-v3' : {
        'sam_name': 'BTagCSVRun2016H-PromptReco-v3',
        'order'     : 0,
        'fillcolor' : 1,
        'fillstyle' : 1,
        'linecolor' : 1,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'Data',
    },
    'BTagCSVRun2016B-23Sep2016-v2' : {
        'sam_name': 'BTagCSVRun2016B-23Sep2016-v2',
        'order'     : 0,
        'fillcolor' : 1,
        'fillstyle' : 1,
        'linecolor' : 1,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'Data',
    },
    'BTagCSVRun2016B-23Sep2016-v3' : {
        'sam_name': 'BTagCSVRun2016B-23Sep2016-v3',
        'order'     : 0,
        'fillcolor' : 1,
        'fillstyle' : 1,
        'linecolor' : 1,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'Data',
    },
    'BTagCSVRun2016C-23Sep2016-v1' : {
        'sam_name': 'BTagCSVRun2016C-23Sep2016-v1',
        'order'     : 0,
        'fillcolor' : 1,
        'fillstyle' : 1,
        'linecolor' : 1,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'Data',
    },
    'BTagCSVRun2016D-23Sep2016-v1' : {
        'sam_name': 'BTagCSVRun2016D-23Sep2016-v1',
        'order'     : 0,
        'fillcolor' : 1,
        'fillstyle' : 1,
        'linecolor' : 1,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'Data',
    },
    'BTagCSVRun2016E-23Sep2016-v1' : {
        'sam_name': 'BTagCSVRun2016E-23Sep2016-v1',
        'order'     : 0,
        'fillcolor' : 1,
        'fillstyle' : 1,
        'linecolor' : 1,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'Data',
    },
    'BTagCSVRun2016F-23Sep2016-v1' : {
        'sam_name': 'BTagCSVRun2016F-23Sep2016-v1',
        'order'     : 0,
        'fillcolor' : 1,
        'fillstyle' : 1,
        'linecolor' : 1,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'Data',
    },
    'BTagCSVRun2016G-23Sep2016-v1' : {
        'sam_name': 'BTagCSVRun2016G-23Sep2016-v1',
        'order'     : 0,
        'fillcolor' : 1,
        'fillstyle' : 1,
        'linecolor' : 1,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'Data',
    },

    ########## MC ##########
    ### Signals
    'HHTo4B_SM' :{
        'sam_name': 'GluGluToHHTo4B_node_SM_13TeV-madgraph-v1',
        'order'     : 2001,
        'fillcolor' : 632-4, 
        'fillstyle' : 1,
        'linecolor' : 632-4,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'SM HH',
    },
    'HHTo4B_BM2' :{
        'sam_name': 'GluGluToHHTo4B_node_BM2_13TeV-madgraph-v1',
        'order'     : 2001,
        'fillcolor' : 616-4, 
        'fillstyle' : 1,
        'linecolor' : 616-4,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'BM2 HH',
    },
    'HHTo4B_BM3' :{
        'sam_name': 'GluGluToHHTo4B_node_BM3_13TeV-madgraph-v1',
        'order'     : 2001,
        'fillcolor' : 432-4, 
        'fillstyle' : 1,
        'linecolor' : 432-4,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'BM3 HH',
    },
    'HHTo4B_BM4' :{
        'sam_name': 'GluGluToHHTo4B_node_BM4_13TeV-madgraph-v1',
        'order'     : 2001,
        'fillcolor' : 600-4, 
        'fillstyle' : 1,
        'linecolor' : 600-4,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'BM4 HH',
    },
    'HHTo4B_BM5' :{
        'sam_name': 'GluGluToHHTo4B_node_BM5_13TeV-madgraph-v1',
        'order'     : 2001,
        'fillcolor' : 416+4, 
        'fillstyle' : 1,
        'linecolor' : 416+4,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'BM5 HH',
    },
    'HHTo4B_BM6' :{
        'sam_name': 'GluGluToHHTo4B_node_BM6_13TeV-madgraph-v1',
        'order'     : 2001,
        'fillcolor' : 400+2, 
        'fillstyle' : 1,
        'linecolor' : 400+2,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'BM6 HH',
    },
    'HHTo4B_BM7' :{
        'sam_name': 'GluGluToHHTo4B_node_BM7_13TeV-madgraph-v1',
        'order'     : 2001,
        'fillcolor' : 800-3, 
        'fillstyle' : 1,
        'linecolor' : 800-3,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'BM7 HH',
    },
    'HHTo4B_BM8' :{
        'sam_name': 'GluGluToHHTo4B_node_BM8_13TeV-madgraph-v1',
        'order'     : 2001,
        'fillcolor' : 920+1, 
        'fillstyle' : 1,
        'linecolor' : 920+1,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'BM8 HH',
    },
    'HHTo4B_BM9' :{
        'sam_name': 'GluGluToHHTo4B_node_BM9_13TeV-madgraph-v1',
        'order'     : 2001,
        'fillcolor' : 860-7, 
        'fillstyle' : 1,
        'linecolor' : 860-7,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'BM9 HH',
    },
    'HHTo4B_BM10' :{
        'sam_name': 'GluGluToHHTo4B_node_BM10_13TeV-madgraph-v1',
        'order'     : 2001,
        'fillcolor' : 800+3, 
        'fillstyle' : 1,
        'linecolor' : 800+3,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'BM10 HH',
    },
    'HHTo4B_BM11' :{
        'sam_name': 'GluGluToHHTo4B_node_BM11_13TeV-madgraph-v1',
        'order'     : 2001,
        'fillcolor' : 840+9, 
        'fillstyle' : 1,
        'linecolor' : 840+9,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'BM11 HH',
    },
    'HHTo4B_BM12' :{
        'sam_name': 'GluGluToHHTo4B_node_BM12_13TeV-madgraph-v1',
        'order'     : 2001,
        'fillcolor' : 880+2, 
        'fillstyle' : 1,
        'linecolor' : 880-2,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'BM12 HH',
    },
    'HHTo4B_BM13' :{
        'sam_name': 'GluGluToHHTo4B_node_BM13_13TeV-madgraph-v1',
        'order'     : 2001,
        'fillcolor' : 900-8,
        'fillstyle' : 1,
        'linecolor' : 900-8,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'BM13 HH',
    },
    'HHTo4B_BMbox' :{
        'sam_name': 'GluGluToHHTo4B_node_BMbox_13TeV-madgraph-v1',
        'order'     : 2001,
        'fillcolor' : 1, 
        'fillstyle' : 1,
        'linecolor' : 1,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'BMbox HH',
    },
    'VBF_HHTo4B_SM' :{
        'sam_name': 'BFHHTo4B_CV_1_C2V_1_C3_1_13TeV-madgraph-v1',
        'order'     : 2002,
        'fillcolor' : 1, 
        'fillstyle' : 1,
        'linecolor' : 1,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'VBF SM HH',
    },

    ### Backgrounds
    'TT' :{
        'sam_name': 'TT_TuneCUETP8M2T4_13TeV-powheg-pythia8-v1',
        'order'     : 4,
        'fillcolor' : 4, #kBlue-2
        'fillstyle' : 1,
        'linecolor' : 4,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'tt',
    },

 # Background QCD
    'QCD_HT300toInf' : { #merged samples
        'sam_name': 'QCD_HT300toInf',
        'order'     : 5,
        'fillcolor' : 415, #kGreen-2
        'fillstyle' : 1,
        'linecolor' : 418,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD HT>300',
    },

    'QCD_HT1000to1500' : {
        'sam_name': 'QCD_HT1000to1500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_v0-v1',
        'order'     : 5,
        'fillcolor' : 415, #kGreen-2
        'fillstyle' : 1,
        'linecolor' : 418,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD',
    },
    'QCD_HT1000to1500_ext' : {
        'sam_name': 'QCD_HT1000to1500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_v0_ext1-v1',
        'order'     : 5,
        'fillcolor' : 415, #kGreen-2
        'fillstyle' : 1,
        'linecolor' : 418,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD',
    },
    'QCD_HT1000to1500_m' : {
        'sam_name': 'QCD_HT1000to1500_merged',
        'order'     : 5,
        'fillcolor' : 415, #kGreen-2
        'fillstyle' : 1,
        'linecolor' : 418,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD',
    },

    'QCD_HT1500to2000' : {
        'sam_name': 'QCD_HT1500to2000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_v0-v1',
        'order'     : 5,
        'fillcolor' : 415, #kGreen-2
        'fillstyle' : 1,
        'linecolor' : 418,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD',
    },
    'QCD_HT1500to2000_ext' : {
        'sam_name': 'QCD_HT1500to2000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_v0_ext1-v1',
        'order'     : 5,
        'fillcolor' : 415, #kGreen-2
        'fillstyle' : 1,
        'linecolor' : 418,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD',
    },
    'QCD_HT1500to2000_m' : {
        'sam_name': 'QCD_HT1500to2000_merged',
        'order'     : 5,
        'fillcolor' : 415, #kGreen-2
        'fillstyle' : 1,
        'linecolor' : 418,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD',
    },
    'QCD_HT2000toInf' : {
        'sam_name': 'QCD_HT2000toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_v0-v1',
        'order'     : 5,
        'fillcolor' : 415, #kGreen-2
        'fillstyle' : 1,
        'linecolor' : 418,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD',
    },
    'QCD_HT2000toInf_ext' : {
        'sam_name': 'QCD_HT2000toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_v0_ext1-v1',
        'order'     : 5,
        'fillcolor' : 415, #kGreen-2
        'fillstyle' : 1,
        'linecolor' : 418,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD',
    },
    'QCD_HT2000toInf_m' : {
        'sam_name': 'QCD_HT2000toInf_merged',
        'order'     : 5,
        'fillcolor' : 415, #kGreen-2
        'fillstyle' : 1,
        'linecolor' : 418,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD',
    },
    'QCD_HT100to200' : {
        'sam_name': 'QCD_HT100to200_BGenFilter_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1',
        'order'     : 5,
        'fillcolor' : 415, #kGreen-2
        'fillstyle' : 1,
        'linecolor' : 418,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD',
    },
    'QCD_HT200to300' : {
        'sam_name': 'QCD_HT200to300_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_v0-v1',
        'order'     : 5,
        'fillcolor' : 415, #kGreen-2
        'fillstyle' : 1,
        'linecolor' : 418,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD',
    },
    'QCD_HT200to300_ext' : {
        'sam_name': 'QCD_HT200to300_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_v0_ext1-v1',
        'order'     : 5,
        'fillcolor' : 415, #kGreen-2
        'fillstyle' : 1,
        'linecolor' : 418,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD',
    },
    'QCD_HT200to300_m' : {
        'sam_name': 'QCD_HT200to300_merged',
        'order'     : 5,
        'fillcolor' : 415, #kGreen-2
        'fillstyle' : 1,
        'linecolor' : 418,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD',
    },
    'QCD_HT300to500' : {
        'sam_name': 'QCD_HT300to500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_v0-v1',
        'order'     : 5,
        'fillcolor' : 415, #kGreen-2
        'fillstyle' : 1,
        'linecolor' : 418,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD',
    },
    'QCD_HT300to500_ext' : {
        'sam_name': 'QCD_HT300to500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_v0_ext1-v2',
        'order'     : 5,
        'fillcolor' : 415, #kGreen-2
        'fillstyle' : 1,
        'linecolor' : 418,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD',
    },
    'QCD_HT300to500_m' : {
        'sam_name': 'QCD_HT300to500_merged',
        'order'     : 5,
        'fillcolor' : 415, #kGreen-2
        'fillstyle' : 1,
        'linecolor' : 418,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD',
    },
    'QCD_HT500to700' : {
        'sam_name': 'QCD_HT500to700_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_v0-v1',
        'order'     : 5,
        'fillcolor' : 415, #kGreen-2
        'fillstyle' : 1,
        'linecolor' : 418,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD',
    },
    'QCD_HT500to700_ext' : {
        'sam_name': 'QCD_HT500to700_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_v0_ext1-v1',
        'order'     : 5,
        'fillcolor' : 415, #kGreen-2
        'fillstyle' : 1,
        'linecolor' : 418,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD',
    },
    'QCD_HT500to700_m' : {
        'sam_name': 'QCD_HT500to700_merged',
        'order'     : 5,
        'fillcolor' : 415, #kGreen-2
        'fillstyle' : 1,
        'linecolor' : 418,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD',
    },
    'QCD_HT700to1000' : {
        'sam_name': 'QCD_HT700to1000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_v0-v1',
        'order'     : 5,
        'fillcolor' : 415, #kGreen-2
        'fillstyle' : 1,
        'linecolor' : 418,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD',
    },
    'QCD_HT700to1000_ext' : {
        'sam_name': 'QCD_HT700to1000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8_v0_ext1-v1',
        'order'     : 5,
        'fillcolor' : 415, #kGreen-2
        'fillstyle' : 1,
       'linecolor' : 418,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD',
    },
    'QCD_HT700to1000_m' : {
        'sam_name': 'QCD_HT700to1000_merged',
        'order'     : 5,
        'fillcolor' : 415, #kGreen-2
        'fillstyle' : 1,
       'linecolor' : 418,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD',
    },

   # Background QCD bEnriched
    'QCD_b' :{
        'sam_name': 'QCD_b', #merged samples
        'order'     : 6,
        'fillcolor' : 416,
        'fillstyle' : 1,
        'linecolor' : 410,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD (bEnr+BGenF)',
    },

    'QCD_bEnriched_HT1000to1500' :{
        'sam_name': 'QCD_bEnriched_HT1000to1500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1',
        'order'     : 6,
        'fillcolor' : 416,
        'fillstyle' : 1,
        'linecolor' : 410,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD (bEnr+BGenF)',
    },
    'QCD_bEnriched_HT100to200' :{
        'sam_name': 'QCD_bEnriched_HT100to200_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1',
        'order'     : 6,
        'fillcolor' : 416,
        'fillstyle' : 1,
        'linecolor' : 410,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD (bEnr+BGenF)',
    },
    'QCD_bEnriched_HT1500to2000' :{
        'sam_name': 'QCD_bEnriched_HT1500to2000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1',
        'order'     : 6,
        'fillcolor' : 416,
        'fillstyle' : 1,
        'linecolor' : 410,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD (bEnr+BGenF)',
    },
    'QCD_bEnriched_HT2000toInf' :{
        'sam_name': 'QCD_bEnriched_HT2000toInf_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1',
        'order'     : 6,
        'fillcolor' : 416,
        'fillstyle' : 1,
        'linecolor' : 410,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD (bEnr+BGenF)',
    },
    'QCD_bEnriched_HT200to300' :{
        'sam_name': 'QCD_bEnriched_HT200to300_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1',
        'order'     : 6,
        'fillcolor' : 416,
        'fillstyle' : 1,
        'linecolor' : 410,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD (bEnr+BGenF)',
    },
    'QCD_bEnriched_HT300to500' :{
        'sam_name': 'QCD_bEnriched_HT300to500_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1',
        'order'     : 6,
        'fillcolor' : 416,
        'fillstyle' : 1,
        'linecolor' : 410,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD (bEnr+BGenF)',
    },
    'QCD_bEnriched_HT500to700' :{
        'sam_name': 'QCD_bEnriched_HT500to700_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1',
        'order'     : 6,
        'fillcolor' : 416,
        'fillstyle' : 1,
        'linecolor' : 410,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD (bEnr+BGenF)',
    },
    'QCD_bEnriched_HT700to1000' :{
        'sam_name': 'QCD_bEnriched_HT700to1000_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1',
        'order'     : 6,
        'fillcolor' : 416,
        'fillstyle' : 1,
        'linecolor' : 410,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD (bEnr+BGenF)',
    },

    # Background QCD BGenFilter FIXME  xsec*br
    'QCD_HT1000to1500_BGenFilter' :{
        'sam_name': 'QCD_HT1000to1500_BGenFilter_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1',
        'order'     : 6,
        'fillcolor' : 416,
        'fillstyle' : 1,
        'linecolor' : 410,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD (bEnr+BGenF)',
    },
    'QCD_HT100to200_BGenFilter' :{
        'sam_name': 'QCD_HT100to200_BGenFilter_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1',
        'order'     : 6,
        'fillcolor' : 416,
        'fillstyle' : 1,
        'linecolor' : 410,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD (bEnr+BGenF)',
    },
    'QCD_HT1500to2000_BGenFilter' :{
        'sam_name': 'QCD_HT1500to2000_BGenFilter_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1',
        'order'     : 6,
        'fillcolor' : 416,
        'fillstyle' : 1,
        'linecolor' : 410,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD (bEnr+BGenF)',
    },
    'QCD_HT2000toInf_BGenFilter' :{
        'sam_name': 'QCD_HT2000toInf_BGenFilter_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1',
        'order'     : 6,
        'fillcolor' : 416,
        'fillstyle' : 1,
        'linecolor' : 410,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD (bEnr+BGenF)',
    },
    'QCD_HT200to300_BGenFilter' :{
        'sam_name': 'QCD_HT200to300_BGenFilter_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1',
        'order'     : 6,
        'fillcolor' : 416,
        'fillstyle' : 1,
        'linecolor' : 410,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD (bEnr+BGenF)',
    },
    'QCD_HT300to500_BGenFilter' :{
        'sam_name': 'QCD_HT300to500_BGenFilter_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1',
        'order'     : 6,
        'fillcolor' : 416,
        'fillstyle' : 1,
        'linecolor' : 410,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD (bEnr+BGenF)',
    },
    'QCD_HT500to700_BGenFilter' :{
        'sam_name': 'QCD_HT500to700_BGenFilter_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1',
        'order'     : 6,
        'fillcolor' : 416,
        'fillstyle' : 1,
        'linecolor' : 410,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD (bEnr+BGenF)',
    },
    'QCD_HT700to1000_BGenFilter' :{
        'sam_name': 'QCD_HT700to1000_BGenFilter_TuneCUETP8M1_13TeV-madgraphMLM-pythia8-v1',
        'order'     : 6,
        'fillcolor' : 416,
        'fillstyle' : 1,
        'linecolor' : 410,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD (bEnr+BGenF)',
    },
   

    ## for trigger studies
    'ST_s-channel_4f_lept' :{
        'sam_name'  : '',
        'order'     : 1001,
        'fillcolor' : 616-4,
        'fillstyle' : 1,
        'linecolor' : 616,
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'ST s-channel',
    },
    'ST_t-channel_4f_lept' :{
        'sam_name'  : 'ST_t-channel_4f_leptonDecays_13TeV-amcatnlo-pythia8_TuneCUETP8M1_withHLT_ext1-v1',
         'order'    : 1002,
        'fillcolor' : 616-2, #kMagenta
        'fillstyle' : 1,
        'linecolor' : 616, #kMagenta
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'ST t-channel',
    },
  
    'ST_t-channel_top_4f_incl' :{
        'sam_name'  : '',
         'order'    : 1002,
        'fillcolor' : 616-2, #kMagenta
        'fillstyle' : 1,
        'linecolor' : 616, #kMagenta
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'ST t-channel top incl',
    },  
    'ST_t-channel_antitop_4f_incl' :{
        'sam_name'  : '',
         'order'    : 1002,
        'fillcolor' : 616-2, #kMagenta
        'fillstyle' : 1,
        'linecolor' : 616, #kMagenta
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'ST t-channel antitop incl',
    },  

    'WJetsToLNu_HT-100To200_ext2' :{    
        'sam_name': '',
        'order'    : 1003,
        'fillcolor' : 430, #kCyan-2
        'fillstyle' : 1,
        'linecolor' : 430, 
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'WJetsToLNu',
    },
    'WJetsToLNu_HT-100To200_ext1' :{    
        'sam_name': '',
        'order'    : 1003,
        'fillcolor' : 430, #kCyan-2
        'fillstyle' : 1,
        'linecolor' : 430, 
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'WJetsToLNu',
    },
    'WJetsToLNu_HT-100To200' :{    
        'sam_name': '',
        'order'    : 1003,
        'fillcolor' : 430, #kCyan-2
        'fillstyle' : 1,
        'linecolor' : 430, 
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'WJetsToLNu',
    },
    'WJetsToLNu_HT-200To400' :{    
        'sam_name':'',
        'order'    : 1003,
        'fillcolor' : 430, #kCyan-2
        'fillstyle' : 1,
        'linecolor' : 430, 
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'WJetsToLNu',
    },
    'WJetsToLNu_HT-200To400_ext1' :{    
        'sam_name':'',
        'order'    : 1003,
        'fillcolor' : 430, #kCyan-2
        'fillstyle' : 1,
        'linecolor' : 430, 
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'WJetsToLNu',
    },
    'WJetsToLNu_HT-200To400_ext2' :{    
        'sam_name':'',
        'order'    : 1003,
        'fillcolor' : 430, #kCyan-2
        'fillstyle' : 1,
        'linecolor' : 430, 
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'WJetsToLNu',
    },
    'WJetsToLNu_HT-400To600' :{    
        'sam_name':'',
          'order'    : 1003,
        'fillcolor' : 430, #kCyan-2
        'fillstyle' : 1,
        'linecolor' : 430, 
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'WJetsToLNu',
    },
    'WJetsToLNu_HT-400To600_ext' :{    
        'sam_name':'',
        'order'    : 1003,
        'fillcolor' : 430, #kCyan-2
        'fillstyle' : 1,
        'linecolor' : 430, 
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'WJetsToLNu',
    },
    'WJetsToLNu_HT-600To800' :{    
        'sam_name':'',
        'order'    : 1003,
        'fillcolor' : 430, #kCyan-2
        'fillstyle' : 1,
        'linecolor' : 430, 
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'WJetsToLNu',
    },
    'WJetsToLNu_HT-600To800_ext' :{    
        'sam_name':'',
        'order'    : 1003,
        'fillcolor' : 430, #kCyan-2
        'fillstyle' : 1,
        'linecolor' : 430, 
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'WJetsToLNu',
    },
    'WJetsToLNu_HT-800To1200' :{    
        'sam_name':'',
        'order'    : 1003,
        'fillcolor' : 430, #kCyan-2
        'fillstyle' : 1,
        'linecolor' : 430, 
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'WJetsToLNu',
    },
    'WJetsToLNu_HT-800To1200_ext' :{    
        'sam_name':'',
         'order'    : 1003,
        'fillcolor' : 430, #kCyan-2
        'fillstyle' : 1,
        'linecolor' : 430, 
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'WJetsToLNu',
   },
    'WJetsToLNu_HT-1200To2500' :{    
        'sam_name':'',
        'order'    : 1003,
        'fillcolor' : 430, #kCyan-2
        'fillstyle' : 1,
        'linecolor' : 430, 
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'WJetsToLNu',
    },
    'WJetsToLNu_HT-1200To2500_ext' :{    
        'sam_name':'',
        'order'    : 1003,
        'fillcolor' : 430, #kCyan-2
        'fillstyle' : 1,
        'linecolor' : 430, 
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'WJetsToLNu',
    },
    'WJetsToLNu_HT-2500ToInf' :{    
        'sam_name':'',
        'order'    : 1003,
        'fillcolor' : 430, #kCyan-2
        'fillstyle' : 1,
        'linecolor' : 430, 
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'WJetsToLNu',
    },   
    'WJetsToLNu_HT-2500ToInf_ext' :{    
        'sam_name':'',
        'order'    : 1003,
        'fillcolor' : 430, #kCyan-2
        'fillstyle' : 1,
        'linecolor' : 430, 
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'WJetsToLNu',
    },   

    #additional samples (for second level filters)
    'QCD_HT200toInf' :{
        'sam_name':'QCD_HT200toInf',
        'order'    : 9999,
        'fillcolor' : 440,
        'fillstyle' : 1,
        'linecolor' : 440, 
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD HT>200',
    },  
    'QCD_HT500toInf' :{
        'sam_name':'QCD_HT500toInf',
        'order'    : 9999,
        'fillcolor' : 430, #kCyan-2
        'fillstyle' : 1,
        'linecolor' : 430, 
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD HT>500',
    },  
    'QCD_HT200to500' :{
        'sam_name':'QCD_HT200to500',
        'order'    : 9999,
        'fillcolor' : 430,
        'fillstyle' : 1,
        'linecolor' : 430, 
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD 200<HT<500',
    },  
    'QCD500_tt_SM300' :{
        'sam_name':'QCD500_tt_SM300',
        'order'    : 9999,
        'fillcolor' : 410,
        'fillstyle' : 1,
        'linecolor' : 410, 
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD HT<500 + tt + 300SM',
    },      
    'QCD500_tt_SM100k' :{
        'sam_name':'QCD500_tt_SM100k',
        'order'    : 9999,
        'fillcolor' : 410,
        'fillstyle' : 1,
        'linecolor' : 410, 
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : 'QCD HT<500 + tt + 100SM',
    },    
    'Data_BDT_28_11_16_15h_sig' :{ #debug
        'sam_name':'Data_BDT_28_11_16_15h_sig',
        'order'    : 9999,
        'fillcolor' : 410,
        'fillstyle' : 1,
        'linecolor' : 410, 
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : '',
    },   
    'Data_BDT_28_11_16_15h_bkg' :{  #debug
        'sam_name':'Data_BDT_28_11_16_15h_bkg',
        'order'    : 9999,
        'fillcolor' : 410,
        'fillstyle' : 1,
        'linecolor' : 410, 
        'linewidth' : 2,
        'linestyle' : 1,
        'label'     : '',
    },  

}
